export * from "./Home";
export * from "./AboutUs";
export * from "./Blogs";
export * from "./Community";
export * from "./ContactUs";
export * from "./Legals";
export * from "./Policy";
export * from "./Terms";
export * from "./TokenSales";
